import { promises as fs } from "node:fs";
import path from "node:path";
import { DcpCandidate, ProjectReport } from "../core/types.js";
import { ensureDirectory } from "../core/fs.js";

export async function generateDcpScaffold(report: ProjectReport): Promise<string[]> {
  const outputDirectory = path.join(report.projectRoot, ".distributivize", "wrappers");
  await ensureDirectory(outputDirectory);
  await cleanGeneratedDirectory(outputDirectory);

  const generated: string[] = [];
  const suitable = report.candidates.filter((candidate) => candidate.score >= 50);

  const indexPath = path.join(outputDirectory, "index.ts");
  await fs.writeFile(indexPath, buildIndex(suitable), "utf8");
  generated.push(indexPath);

  for (const candidate of suitable.slice(0, 12)) {
    const fileName = `${slug(candidate.id)}.dcp.ts`;
    const filePath = path.join(outputDirectory, fileName);
    await fs.writeFile(filePath, buildWrapper(candidate), "utf8");
    generated.push(filePath);
  }

  return generated;
}

async function cleanGeneratedDirectory(outputDirectory: string): Promise<void> {
  const entries = await fs.readdir(outputDirectory, { withFileTypes: true });
  await Promise.all(
    entries
      .filter((entry) => entry.isFile() && (entry.name.endsWith(".dcp.ts") || entry.name === "index.ts"))
      .map((entry) => fs.unlink(path.join(outputDirectory, entry.name)))
  );
}

function buildIndex(candidates: DcpCandidate[]): string {
  const exports = candidates
    .slice(0, 12)
    .map((candidate) => `export * from "./${slug(candidate.id)}.dcp.js";`)
    .join("\n");

  return `// Generated by distributivize. Review before running in production.
${exports || "// No medium/high suitability candidates were found."}
`;
}

function buildWrapper(candidate: DcpCandidate): string {
  const functionName = `run${toPascal(candidate.name)}OnDcp`;
  const sourceImportComment =
    candidate.language === "javascript"
      ? `// TODO: import the original function from "../../${candidate.location.file}".`
      : `// TODO: expose this ${candidate.language} workload through a JS-callable boundary or rewrite the pure kernel in JS for DCP.`;

  return `// Generated by distributivize for ${candidate.location.file}:${candidate.location.startLine}
// Suitability score: ${candidate.score}/100
// Candidate: ${candidate.name} (${candidate.kind})
//
// This is scaffold code. Wire it to your DCP client package and original workload.

${sourceImportComment}

export interface DcpBatch<TInput> {
  items: TInput[];
  metadata?: Record<string, unknown>;
}

export interface DcpResult<TResult> {
  results: TResult[];
  diagnostics: {
    candidateId: string;
    score: number;
    granularity: string;
  };
}

export async function ${functionName}<TInput, TResult>(
  batch: DcpBatch<TInput>,
  options: {
    taskSize?: number;
    retries?: number;
  } = {}
): Promise<DcpResult<TResult>> {
  const taskSize = options.taskSize ?? recommendedTaskSize(batch.items.length);
  const chunks = chunk(batch.items, taskSize);

  // TODO: Replace this local Promise.all with DCP job submission.
  // DCP shape:
  // 1. serialize each chunk as explicit worker input
  // 2. execute a pure worker function with no hidden shared state
  // 3. return compact partial results
  // 4. reduce/merge results after all tasks complete
  const nestedResults = await Promise.all(
    chunks.map(async (items) => {
      return items.map((_item) => {
        throw new Error("Connect this scaffold to the original workload and DCP runtime.");
      }) as TResult[];
    })
  );

  return {
    results: nestedResults.flat(),
    diagnostics: {
      candidateId: ${JSON.stringify(candidate.id)},
      score: ${candidate.score},
      granularity: ${JSON.stringify(candidate.granularity)}
    }
  };
}

function recommendedTaskSize(totalItems: number): number {
  if (totalItems <= 100) return Math.max(1, totalItems);
  if (totalItems <= 10_000) return 250;
  return 1_000;
}

function chunk<T>(items: T[], size: number): T[][] {
  const chunks: T[][] = [];
  for (let index = 0; index < items.length; index += size) {
    chunks.push(items.slice(index, index + size));
  }
  return chunks;
}

/*
Detected snippet:
${indentForComment(candidate.snippet)}

Migration notes:
${candidate.evidence.map((item) => `- ${item}`).join("\n") || "- No specific positive signal was recorded."}
${candidate.serializationConcerns.map((item) => `- Serialization: ${item}`).join("\n")}
${candidate.sharedStateWarnings.map((item) => `- Shared state: ${item}`).join("\n")}
${candidate.batchingRecommendations.map((item) => `- Batching: ${item}`).join("\n")}
*/
`;
}

function slug(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 80);
}

function toPascal(value: string): string {
  const pascal = value
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join("");
  return pascal || "Candidate";
}

function indentForComment(snippet: string): string {
  return snippet
    .split("\n")
    .map((line) => `  ${line}`)
    .join("\n");
}
